create table curso (
       id bigint  GENERATED BY DEFAULT AS IDENTITY,
        categoria varchar(255),
        nome varchar(255),
        primary key (id)
    );
    create table perfil (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome varchar(255),
        primary key (id)
    );

    create table resposta (
       id bigint GENERATED BY DEFAULT AS IDENTITY,
        data_criacao timestamp,
        mensagem varchar(255),
        solucao boolean,
        autor_id bigint,
        topico_id bigint,
        primary key (id)
    );
    create table topico (
       id bigint GENERATED BY DEFAULT AS IDENTITY,
        data_criacao timestamp,
        mensagem varchar(255),
        status varchar(255),
        titulo varchar(255),
        autor_id bigint,
        curso_id bigint,
        primary key (id)
    );
    create table usuario (
       id bigint GENERATED BY DEFAULT AS IDENTITY,
        email varchar(255),
        nome varchar(255),
        senha varchar(255),
        primary key (id)
    );
    create table usuario_perfis (
       usuario_id bigint not null,
        perfis_id bigint not null
    );

    alter table resposta
       add constraint FK9999kvnmdq63ah7imctrl06r7
       foreign key (autor_id)
       references usuario;

    alter table resposta
       add constraint FKltuv9rkfjtlmn8b0rb3wdbjsv
       foreign key (topico_id)
       references topico;

    alter table topico
       add constraint FKsk04hscorwqdymnafg8882v64
       foreign key (autor_id)
       references usuario;

    alter table topico
       add constraint FKcaaogjo0ynd54updie6kdpxd1
       foreign key (curso_id)
       references curso;

    alter table usuario_perfis
       add constraint FK7bhs80brgvo80vhme3u8m6ive
       foreign key (perfis_id)
       references perfil;

    alter table usuario_perfis
       add constraint FKs91tgiyagbilt959wbufiphgc
       foreign key (usuario_id)
       references usuario;